name: Assign Label on Merge

on:
  pull_request:
    types: [closed]

jobs:
  assign-label-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      
      - name: Assign Label to PR
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['done']
            })
        env:
          CRM_PULL_REQUEST_TOKEN: ${{ secrets.CRM_PULL_REQUEST_TOKEN }}

      - name: Find Connected Issue
        id: find_issue
        run: |
          issue_number=$(jq --raw-output '.pull_request.body | capture("#(?<issue_number>[0-9]+)") | .issue_number' $GITHUB_EVENT_PATH)
          echo "::set-output name=issue_number::$issue_number"
      
      - name: Assign Label to Issue
        if: steps.find_issue.outputs.issue_number != ''
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.find_issue.outputs.issue_number }},
              labels: ['done']
            })
        env:
          CRM_PULL_REQUEST_TOKEN: ${{ secrets.CRM_PULL_REQUEST_TOKEN }}
